language: java
jdk:
- oraclejdk16
cache:
  directories:
  - $HOME/.m2
before_install:
  - git update-index --chmod=+x mvnw
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test