arch: amd64
language: java
jdk:
- oraclejdk16
os:
- linux
- osx
dist: xenial
cache:
  directories:
  - $HOME/.m2
before_install:
  - git update-index --chmod=+x mvnw
script:
  - java --version
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
