arch: amd64

sudo: required
language: java
jdk:
- oraclejdk16
os:
- linux
- osx
cache:
  directories:
  - $HOME/.m2

script:
  - java --version
  - mvn clean install
  - ./mvnw clean install
  - mvn test -B
  - ./mvnw test -B
