GET http://localhost:8080/customeraccounts/register 

###

POST http://localhost:8080/customeraccounts/register 
Content-Type: application/json

{
    "name": "Linh",
    "password": "1234er"
    "email": "s234@gmail.com"
    "phone": "09145456789"
    "address": "234 tran hung dao"
}

###

GET http://localhost:8080/customeraccounts/login


###

POST http://localhost:8080/customeraccounts/login
Content-Type: application/json

{
    "name": "Linh",
    "password": "1234er"
}

###



POST http://localhost:8080/customeraccounts/tokenIsValid
